@startuml

class User
{
    - userId
    -firstName
    -lastName
    -email
    -birthday
}

class UserModel
{
    -create(User)
}

class userFactory
{
    + static fromArray(array $user):user
}

class UserValidation
{   
    User user
    Array <ValidationResult> result
    bool isValid 
    + UserValidation(User user)
    + validate();

    -firstNameValid:ValidationResult
    -lastNameValid:ValidationResult


    + UserValidation(User user)
    - isRequiredFirstName():ValidationResult
    - isRequiredlasttName():ValidationResult
    - isRequiredEmail():ValidationResult
    + getIsValid()
    + getErrors():array<ValidationResult>
}

class ValidationResult
{
    
    + message:string
    + isValid:bool
    + value:any
}




@enduml


$elencovalidazione = []

//$val->addName('email)
$elencovalidazione['email']=[
    'value'=>'mail@it',
    'pattern'=>'email',
    'required'=>true

]
$elencovalidazione['age']=[
    'value'=>'29',
    'min'=>'18',
    'max'=>'99',
    'pattern'=>'email',
    'required'=>true

]